server:
  port: 8080

spring:
  application:
    name: order-service
  data:
    cassandra:
      keyspace-name: orders
      contact-points: ${CASSANDRA_CONTACT_POINTS}
      port: ${CASSANDRA_PORT}
      local-datacenter: ${CASSANDRA_DATACENTER}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: health,info, prometheus

eureka:
  instance:
    prefer-ip-address: true
    hostname: eureka-server
  client:
    service-url:
      defaultZone: http://${EUREKA_INSTANCE_HOSTNAME}:${EUREKA_SERVER_PORT}/eureka
    register-with-eureka: true
    fetch-registry: true


