spring:
  application:
    name: order_service
  data:
    cassandra:
      keyspace-name: orders
      contact-points: localhost
      port: 9042
      local-datacenter: datacenter1
server:
  port: 8083

