server:
  port: 8080

spring:
  application:
    name: order-service
  cassandra:
      keyspace-name: orders
      contact-points: ${CASSANDRA_CONTACT_POINTS}
      port: ${CASSANDRA_PORT}
      local-datacenter: ${CASSANDRA_DATACENTER}

management:
  endpoints:
    web:
      exposure:
        include: health,info, prometheus


